CREATE TABLE Users (
  ID INTEGER PRIMARY KEY,
  Email VARCHAR(255) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  DateOfBirth DATE NOT NULL,
  PhoneNumber VARCHAR(20),
  Address VARCHAR(255),
  AccountType VARCHAR(20) NOT NULL,
  AccountStatus VARCHAR(20) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL
);
